### ISSUE TITLE
suggestion: C implementation

### ISSUE THREAD

**Issue by ashlinrichardson** [Subho07/MF4CF#1]
Dear Dr. Dey,
Feeling very impressed by your paper and especially that you chose to share your code online -- I was inspired to create a C implementation of your algorithm..

.. [please click here if you would like to see the draft version of that](https://github.com/ashlinrichardson/MF4CF/blob/master/MF4C.c)

..the above code should work on any OS and has "no dependencies" (except a C compiler). Without expectation of any particular outcome: would you be open to considering contribution to your code repository, with a C translation like that sometime in the future?

If so there are a few further revisions to it I would be happy to make before submitting it for your review:
- writing envi headers
- optimizations to variables access
- using the moving window pattern from PolSARPro to make the filtering step a best-practice

Your thoughts? Hope to hear your feedback

Many thanks
cheers

Ashlin

**Comment by Subho07** [comment]
Dear Dr. Richardson,

I appreciate your interest in our work.  I am open to the idea that you have suggested and I highly like the C translation of the code. Could you please contact me at sdey2307@gmail.com for further discussion on this topic?

Thanks and regards,
Subhadip
